### PR TITLE
go linter fixes and updates

### PR DESCRIPTION
**Pull request by matevz**
This PR:
- Fixes golangci-lint G204 error for
  go/oasis-test-runner/scenario/e2e/txsource.go,
- Docker: Bumps golangci-lint to 1.23.6,
- Makefile: Uses golangci-lint --timeout instead of obsolete --deadline.

### CODE REVIEW

**Comment by ptrus** [comment]
also updating golangci would make sense :)

**Comment by matevz** [comment]
Replaced make lint's `--deadline` with `--timeout` flag.

**Comment by matevz** [comment]
> also updating golangci would make sense :)

Should I just bump the version here or is there something else I missed? https://github.com/oasislabs/oasis-core/blob/master/docker/development/Dockerfile#L7

**Comment by matevz** [comment]
New `oasislabs/testing:0.3.0` and `oasislabs/development:0.3.0` docker images are now pushed.

**Pull request merged**
